create table temp (
                    id number generated as IDENTITY,
                    text varchar2(100)
                    );
                    
insert into temp (id, text)
values (1,
        'Test With 1'
        ); -- SQL Error: ORA-32795: cannot insert into a generated always identity column

drop table temp;

--------------------------------------------------------------------------------

create table temp (
                    id number generated always as identity,
                    text varchar2(100)
                    );
                    
insert into temp (id, text)
values (1,
        'Test With 1'
        ); -- SQL Error: ORA-32795: cannot insert into a generated always identity column
        
insert into temp (id, text)
values (null,
        'Test With null'
        ); -- SQL Error: ORA-32795: cannot insert into a generated always identity column
        
insert into temp(text)
values ('Test With No Value');

insert into temp(text)
values ('Test With No Value');

insert into temp(text)
values ('Test With No Value');

insert into temp(text)
values ('Test With No Value');

select * from temp;

drop table temp;

--------------------------------------------------------------------------------

create table temp (
                    id number generated by default as identity,
                    text varchar2(100)
                    );
                    
insert into temp (id, text)
values (1,
        'Test With 1'
        );
        
insert into temp (id, text)
values (20,
        'Test With 20'
        );
        
select * from temp;

insert into temp (id, text)
values (null,
        'Test With null'
        ); -- SQL Error: ORA-01400: cannot insert NULL into ("HR"."TEMP"."ID")
        
insert into temp(text)
values ('Test With No Value');

select * from temp;

-- Select Table Name, Press SHIFT+F4 to see Name of Te Sequence Generated By Server for Identity Column.

select * from user_objects
where object_name = 'ISEQ$$_76781';

select * from user_sequences
where sequence_name = 'ISEQ$$_76781';

select ISEQ$$_76781.nextval from dual;
select ISEQ$$_76781.nextval from dual;
select ISEQ$$_76781.nextval from dual;
select ISEQ$$_76781.nextval from dual;
select ISEQ$$_76781.nextval from dual;
select ISEQ$$_76781.nextval from dual;

insert into temp(text)
values ('Test With No Value');

select * from temp;

drop table temp;

--------------------------------------------------------------------------------

create table temp (
                    id number generated by default on null as identity,
                    text varchar2(100)
                    );
                    
insert into temp (id, text)
values (1,
        'Test With 1'
        );
        
insert into temp (id, text)
values (null,
        'Test With null'
        );
        
insert into temp(text)
values ('Test With No Value');

select * from temp;

drop table temp;

--------------------------------------------------------------------------------

create table temp (
                    id number generated by default on null as identity start with 50 increment by 3,
                    text varchar2(100)
                    );
                    
insert into temp (id, text)
values (1,
        'Test With 1'
        );
        
insert into temp (id, text)
values (20,
        'Test With 20'
        );

select * from temp;

insert into temp (id, text)
values (null,
        'Test With null'
        );
        
select * from temp;

insert into temp (id, text)
values (null,
        'Test With null'
        );
        
insert into temp (id, text)
values (null,
        'Test With null'
        );
        
insert into temp (id, text)
values (null,
        'Test With null'
        );
        
insert into temp (id, text)
values (null,
        'Test With null'
        );

select * from temp;

insert into temp(text)
values ('Test With No Value');

select * from temp;

select * from user_sequences
where sequence_name = 'ISEQ$$_76785';

drop table temp;

select * from user_sequences
where sequence_name = 'ISEQ$$_76785'; -- Oracle Keeps The Sequence Alive even after Table is Dropped
                                      -- in case If We Want to Flashback The Table.

purge recyclebin;

select * from user_sequences
where sequence_name = 'ISEQ$$_76785'; -- Sequence is Dropped Automatically by Oracle Server after
                                      -- table is Purged from Recycle Bin.